routes/admin.php
<?php


Auth::routes();

Route::get('/', 'HomeController@index')->name('dashboard');
Route::get('/home', 'HomeController@index')->name('dashboard');
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('about', 'HomeController@index');

Route::resource('roles', 'RoleController');

Route::resource('modules', 'ModuleController');

Route::get('/module/step1/{id?}', 'ModuleController@getStep1')->name('modules.create');
Route::get('/module/step2/{tablename?}', 'ModuleController@getStep2')->name('modules.create');
Route::get('/getJoinFields/{tablename?}', 'ModuleController@getJoinFields');
Route::get('/module/step3/{tablename?}', 'ModuleController@getStep3')->name('modules.create');

Route::post('/step1', 'ModuleController@postStep1');
Route::post('/step2', 'ModuleController@postStep2');
Route::post('/step3', 'ModuleController@postStep3');


Route::resource('users', 'UserController');

Route::resource('permissions', 'PermissionController');

//Route::resource('profile', 'UserController');

Route::get('user/profile', 'UserController@profile')->name('users.profile');
//Route::patch('users/profile-update/{id}', 'UserController@profileUpdate')->name('users.profile-update');

Route::resource('languages', 'LanguageController');

Route::resource('pages', 'PageController');

Route::resource('contactus', 'ContactUsController');

Route::resource('notifications', 'NotificationController');

Route::resource('menus', 'MenuController');

//Menu #TODO need to be fixed
Route::get('statusChange/{id}', 'MenuController@statusChange');

Route::post('updateChannelPosition', 'MenuController@update_channel_position')->name('channels');
Route::resource('settings', 'SettingController');

Route::resource('subscriptions', 'SubscriptionController');

Route::resource('courses', 'CourseController');

Route::resource('chapters', 'ChapterController');

Route::resource('chapter-ages', 'ChapterAgeController');

Route::resource('chapter-pages', 'ChapterPageController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});
Route::get('/index2', function () {
    return view('index2');
});
Route::get('/index3', function () {
    return view('index3');
});
Route::get('/about', function () {
    return view('about');
});
Route::get('/contact', function () {
    return view('contact');
});
Route::get('/blog', function () {
    return view('blog');
});
Route::get('/courses', function () {
    return view('courses');
});
Route::get('/faq', function () {
    return view('faq');
})->name('faq');
Route::get('/membership', function () {
    return view('membership');
});
Route::get('/portfolio', function () {
    return view('portfolio');
});

Route::get('/loginuser', function () {
    return view('loginuser');
})->name('loginuser');
Route::get('/registeruser', 'HomeController@register')->name('registeruser');
Route::get('/event', function () {
    return view('event');
});
Route::get('/event-details', function () {
    return view('event-details');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/redirectgoogle', 'GoogleLoginController@redirectToProvider')->name('redirectgoogle');
Route::get('/callbackgoogle', 'GoogleLoginController@handleProviderCallback')->name('callbackgoogle');
Route::get('/redirect', 'SocialAuthFacebookController@redirect')->name('redirect');
Route::get('/callback', 'SocialAuthFacebookController@callback');
Route::get('/profile', 'Web\ProfileController@index')->name('profile');

app/Models/Chapter.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @property integer id
 * @property string name
 * @property string created_at
 * @property string updated_at
 * @property string deleted_at
 *
 * @SWG\Definition(
 *      definition="Chapter",
 *      required={"name"},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="name",
 *          description="name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="deleted_at",
 *          description="deleted_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class Chapter extends Model
{
    use SoftDeletes;

    public $table = 'chapters';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'name',
        'course_id',
        'details',
        'image',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id'   => 'integer',
        'name' => 'string'
    ];

    /**
     * The objects that should be append to toArray.
     *
     * @var array
     */
    protected $with = [];

    /**
     * The attributes that should be append to toArray.
     *
     * @var array
     */
    protected $appends = [];

    /**
     * The attributes that should be visible in toArray.
     *
     * @var array
     */
    protected $visible = [];

    /**
     * Validation create rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required',
//        'course_id' => 'required',
    ];

    /**
     * Validation update rules
     *
     * @var array
     */
    public static $update_rules = [
        'name' => 'required'
    ];

    /**
     * Validation api rules
     *
     * @var array
     */
    public static $api_rules = [
        'name' => 'required'
    ];

    /**
     * Validation api update rules
     *
     * @var array
     */
    public static $api_update_rules = [
        'name' => 'required'
    ];

    public function course()
    {
        return $this->belongsTo(Course::class);
    }

    public function pages()
    {
        return $this->hasMany(ChapterPage::class, 'chapter_id');
    }

    public function getImageUrlAttribute()
    {
        return ($this->image && storage_path(url('storage/app/' . $this->image))) ? route('api.resize', ['img' => $this->image]) : route('api.resize', ['img' => 'users/book.png', 'w=100', 'h=100']);
    }

}

app/Http/Controllers/Admin/ChapterController.php
<?php

namespace App\Http\Controllers\Admin;

use App\DataTables\Admin\ChapterPageDataTable;
use App\DataTables\Admin\PageDataTable;
use App\Helper\BreadcrumbsRegister;
use App\DataTables\Admin\ChapterDataTable;
use App\Http\Requests\Admin;
use App\Http\Requests\Admin\CreateChapterRequest;
use App\Http\Requests\Admin\UpdateChapterRequest;
use App\Repositories\Admin\ChapterRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Laracasts\Flash\Flash;
use Illuminate\Http\Response;

class ChapterController extends AppBaseController
{
    /** ModelName */
    private $ModelName;

    /** BreadCrumbName */
    private $BreadCrumbName;

    /** @var  ChapterRepository */
    private $chapterRepository;

    public function __construct(ChapterRepository $chapterRepo)
    {
        $this->chapterRepository = $chapterRepo;
        $this->ModelName = 'chapters';
        $this->BreadCrumbName = 'Chapters';
    }

    /**
     * Display a listing of the Chapter.
     *
     * @param ChapterDataTable $chapterDataTable
     * @return Response
     */
    public function index(ChapterDataTable $chapterDataTable)
    {
        BreadcrumbsRegister::Register($this->ModelName, $this->BreadCrumbName);
        return $chapterDataTable->render('admin.chapters.index', ['title' => $this->BreadCrumbName]);
    }

    /**
     * Show the form for creating a new Chapter.
     *
     * @return Response
     */
    public function create(Request $request)
    {
        BreadcrumbsRegister::Register($this->ModelName, $this->BreadCrumbName);
        return view('admin.chapters.create')->with([
            'title'     => $this->BreadCrumbName,
            'course_id' => $request->get('course_id'),
        ]);

    }

    /**
     * Store a newly created Chapter in storage.
     *
     * @param CreateChapterRequest $request
     *
     * @return Response
     */
    public function store(CreateChapterRequest $request)
    {
        $chapter = $this->chapterRepository->saveRecord($request);

        Flash::success($this->BreadCrumbName . ' saved successfully.');
        if (isset($request->continue)) {
            $redirect_to = redirect(route('admin.chapters.create'));
        } elseif (isset($request->translation)) {
            $redirect_to = redirect(route('admin.chapters.edit', $chapter->id));
        } else {
            $redirect_to = redirect(route('admin.courses.show', [$chapter->course_id]));
        }
        return $redirect_to->with([
            'title' => $this->BreadCrumbName
        ]);
    }

    /**
     * Display the specified Chapter.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id, ChapterPageDataTable $pageDataTable)
    {
        $chapter = $this->chapterRepository->findWithoutFail($id);
        $pageDataTable->chapter_id = $id;
        if (empty($chapter)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.chapters.index'));
        }

        BreadcrumbsRegister::Register($this->ModelName, $this->BreadCrumbName, $chapter);
        return $pageDataTable->render('admin.chapters.show', [
            'chapter' => $chapter,
            'title'   => $this->BreadCrumbName]);
//        return view('admin.chapters.show')->with(['chapter' => $chapter, 'title' => $this->BreadCrumbName]);
    }

    /**
     * Show the form for editing the specified Chapter.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $chapter = $this->chapterRepository->findWithoutFail($id);

        if (empty($chapter)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.chapters.index'));
        }

        BreadcrumbsRegister::Register($this->ModelName, $this->BreadCrumbName, $chapter);
        return view('admin.chapters.edit')->with(['chapter' => $chapter, 'title' => $this->BreadCrumbName]);
    }

    /**
     * Update the specified Chapter in storage.
     *
     * @param int $id
     * @param UpdateChapterRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateChapterRequest $request)
    {

        $chapter = $this->chapterRepository->findWithoutFail($id);

        if (empty($chapter)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.chapters.index'));
        }

        $chapter = $this->chapterRepository->updateRecord($request, $chapter);

        Flash::success($this->BreadCrumbName . ' updated successfully.');
//        if (isset($request->continue)) {
//            $redirect_to = redirect(route('admin.chapters.create'));
//        } else {
//            $redirect_to = redirect(route('admin.chapters.index'));
//        }
        $redirect_to = redirect(route('admin.courses.show', [$chapter->course_id]));
        return $redirect_to->with(['title' => $this->BreadCrumbName]);
    }

    /**
     * Remove the specified Chapter from storage.
     *
     * @param int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $chapter = $this->chapterRepository->findWithoutFail($id);

        if (empty($chapter)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.chapters.index'));
        }

        $this->chapterRepository->deleteRecord($id);

        Flash::success($this->BreadCrumbName . ' deleted successfully.');
        return redirect(route('admin.chapters.index'))->with(['title' => $this->BreadCrumbName]);
    }
}

resources/views/admin/chapters/create.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content')
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'admin.chapters.store', 'files' => true]) !!}

                        @include('admin.chapters.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/chapters/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.chapters.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    @ability('super-admin' ,'chapters.show')
    <a href="{{ route('admin.chapters.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    @endability
    @ability('super-admin' ,'chapters.edit')
    <a href="{{ route('admin.chapters.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    @endability
    @ability('super-admin' ,'chapters.destroy')
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
    ]) !!}
    @endability
</div>
{!! Form::close() !!}

resources/views/admin/chapters/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $chapter->name }} <small>{{ $title }}</small>
@endsection

@section('content')
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($chapter, ['route' => ['admin.chapters.update', $chapter->id], 'method' => 'patch', 'files' => true]) !!}

                        @include('admin.chapters.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/chapters/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Chapter Title:') !!}
    {!! Form::text('name', null, ['class' => 'form-control', 'placeholder'=>'Enter Title']) !!}
    {!! Form::hidden('course_id', isset($course_id) ? $course_id: null, ['class' => 'form-control', 'placeholder'=>'Enter Title']) !!}
</div>
<div class="clearfix"></div>
<div class="form-group col-sm-12">
    {!! Form::label('details', 'Description:') !!}
    {!! Form::textarea('details', null, ['class' => 'form-control', 'placeholder'=>'Enter Description']) !!}
</div>
<div class="form-group col-sm-6">
    {!! Form::label('image', 'Image:') !!}
    {!! Form::file('image', null, ['class' => 'form-control']) !!}
</div>
<div class="clearfix"></div>
@isset($chapter)
    <div class="form-group col-sm-3">
        <img src="{{$chapter->image_url}}" width="100%"/>
    </div>
@endisset

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    @if(!isset($chapter))
        {!! Form::submit(__('Save And Add Translations'), ['class' => 'btn btn-primary', 'name'=>'translation']) !!}
    @endif
    {!! Form::submit(__('Save And Add More'), ['class' => 'btn btn-primary', 'name'=>'continue']) !!}
    <a href="{!! route('admin.chapters.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/admin/chapters/index.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content')
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('admin.chapters.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/admin/chapters/show.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content')
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    <dl class="dl-horizontal">
                        @include('admin.chapters.show_fields')
                    </dl>
                    {!! Form::open(['route' => ['admin.chapters.destroy', $chapter->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        @ability('super-admin' ,'chapters.show')
                        <a href="{!! route('admin.chapters.index') !!}" class="btn btn-default">
                            <i class="glyphicon glyphicon-arrow-left"></i> Back
                        </a>
                        @endability
                    </div>
                    <div class='btn-group'>
                        @ability('super-admin' ,'chapters.edit')
                        <a href="{{ route('admin.chapters.edit', $chapter->id) }}" class='btn btn-default'>
                            <i class="glyphicon glyphicon-edit"></i> Edit
                        </a>
                        @endability
                    </div>
                    <div class='btn-group'>
                        @ability('super-admin' ,'chapters.destroy')
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i> Delete', [
                            'type' => 'submit',
                            'class' => 'btn btn-danger',
                            'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
                        ]) !!}
                        @endability
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h2 class="box-title">Add Pages</h2>
            </div>
            <div class="box-body">
                <div class="row datatable-action-urls"
                     data-action-create="{{route('admin.chapter-pages.create',['chapter_id'=>$chapter->id])}}">
                    <div class="col-sm-12">
                        @include('admin.pages.table')
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/chapters/show_fields.blade.php
<!-- Name Field -->
<dt>{!! Form::label('name', 'Name:') !!}</dt>
<dd>{!! $chapter->name !!}</dd>

<dt>{!! Form::label('details', 'Description:') !!}</dt>
<dd>{!! $chapter->details !!}</dd>

resources/views/admin/chapters/table.blade.php
@push('css')
    @include('admin.layouts.datatables_css')
@endpush

{!! $dataTable->table(['width' => '100%']) !!}

@push('scripts')
    @include('admin.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush