routes/admin.php
<?php


Auth::routes();

Route::get('/', 'HomeController@index')->name('dashboard');
Route::get('/home', 'HomeController@index')->name('dashboard');
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('about', 'HomeController@index');

Route::resource('roles', 'RoleController');

Route::resource('modules', 'ModuleController');

Route::get('/module/step1/{id?}', 'ModuleController@getStep1')->name('modules.create');
Route::get('/module/step2/{tablename?}', 'ModuleController@getStep2')->name('modules.create');
Route::get('/getJoinFields/{tablename?}', 'ModuleController@getJoinFields');
Route::get('/module/step3/{tablename?}', 'ModuleController@getStep3')->name('modules.create');

Route::post('/step1', 'ModuleController@postStep1');
Route::post('/step2', 'ModuleController@postStep2');
Route::post('/step3', 'ModuleController@postStep3');


Route::resource('users', 'UserController');

Route::resource('permissions', 'PermissionController');

//Route::resource('profile', 'UserController');

Route::get('user/profile', 'UserController@profile')->name('users.profile');
//Route::patch('users/profile-update/{id}', 'UserController@profileUpdate')->name('users.profile-update');

Route::resource('languages', 'LanguageController');

Route::resource('pages', 'PageController');

Route::resource('contactus', 'ContactUsController');

Route::resource('notifications', 'NotificationController');

Route::resource('menus', 'MenuController');

//Menu #TODO need to be fixed
Route::get('statusChange/{id}', 'MenuController@statusChange');

Route::post('updateChannelPosition', 'MenuController@update_channel_position')->name('channels');
Route::resource('settings', 'SettingController');

Route::resource('subscriptions', 'SubscriptionController');

Route::resource('courses', 'CourseController');

Route::resource('chapters', 'ChapterController');

Route::resource('chapter-ages', 'ChapterAgeController');

Route::resource('chapter-pages', 'ChapterPageController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});
Route::get('/index2', function () {
    return view('index2');
});
Route::get('/index3', function () {
    return view('index3');
});
Route::get('/about', function () {
    return view('about');
});
Route::get('/contact', function () {
    return view('contact');
});
Route::get('/blog', function () {
    return view('blog');
});
Route::get('/courses', function () {
    return view('courses');
});
Route::get('/faq', function () {
    return view('faq');
})->name('faq');
Route::get('/membership', function () {
    return view('membership');
});
Route::get('/portfolio', function () {
    return view('portfolio');
});

Route::get('/loginuser', function () {
    return view('loginuser');
})->name('loginuser');
Route::get('/registeruser', 'HomeController@register')->name('registeruser');
Route::get('/event', function () {
    return view('event');
});
Route::get('/event-details', function () {
    return view('event-details');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/redirectgoogle', 'GoogleLoginController@redirectToProvider')->name('redirectgoogle');
Route::get('/callbackgoogle', 'GoogleLoginController@handleProviderCallback')->name('callbackgoogle');
Route::get('/redirect', 'SocialAuthFacebookController@redirect')->name('redirect');
Route::get('/callback', 'SocialAuthFacebookController@callback');
Route::get('/profile', 'Web\ProfileController@index')->name('profile');

app/Models/ChapterPage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @property integer id
 * @property string name
 * @property string created_at
 * @property string updated_at
 * @property string deleted_at
 *
 * @SWG\Definition(
 *      definition="ChapterPage",
 *      required={"chapter_id", "number", "text"},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="chapter_id",
 *          description="chapter_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="number",
 *          description="number",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="text",
 *          description="text",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="deleted_at",
 *          description="deleted_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class ChapterPage extends Model
{
    use SoftDeletes;

    public $table = 'chapter_pages';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'chapter_id',
        'number',
        'details'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id'         => 'integer',
        'chapter_id' => 'integer',
        'number'     => 'string',
        'text'       => 'string'
    ];

    /**
     * The objects that should be append to toArray.
     *
     * @var array
     */
    protected $with = [];

    /**
     * The attributes that should be append to toArray.
     *
     * @var array
     */
    protected $appends = [];

    /**
     * The attributes that should be visible in toArray.
     *
     * @var array
     */
    protected $visible = [];

    /**
     * Validation create rules
     *
     * @var array
     */
    public static $rules = [
        'chapter_id' => 'required',
        'number'     => 'required',
        'details'    => 'required'
    ];

    /**
     * Validation update rules
     *
     * @var array
     */
    public static $update_rules = [
        'chapter_id' => 'required',
        'number'     => 'required',
        'details'    => 'required'
    ];

    /**
     * Validation api rules
     *
     * @var array
     */
    public static $api_rules = [
        'chapter_id' => 'required',
        'number'     => 'required',
        'details'    => 'required'
    ];

    /**
     * Validation api update rules
     *
     * @var array
     */
    public static $api_update_rules = [
        'chapter_id' => 'required',
        'number'     => 'required',
        'details'    => 'required'
    ];

    public function chapter()
    {
        return $this->belongsTo(Chapter::class);
    }

}

app/Http/Controllers/Admin/ChapterPageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helper\BreadcrumbsRegister;
use App\DataTables\Admin\ChapterPageDataTable;
use App\Http\Requests\Admin;
use App\Http\Requests\Admin\CreateChapterPageRequest;
use App\Http\Requests\Admin\UpdateChapterPageRequest;
use App\Repositories\Admin\ChapterPageRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Laracasts\Flash\Flash;
use Illuminate\Http\Response;

class ChapterPageController extends AppBaseController
{
    /** ModelName */
    private $ModelName;

    /** BreadCrumbName */
    private $BreadCrumbName;

    /** @var  ChapterPageRepository */
    private $chapterPageRepository;

    public function __construct(ChapterPageRepository $chapterPageRepo)
    {
        $this->chapterPageRepository = $chapterPageRepo;
        $this->ModelName = 'chapter-pages';
        $this->BreadCrumbName = 'Chapter Pages';
    }

    /**
     * Display a listing of the ChapterPage.
     *
     * @param ChapterPageDataTable $chapterPageDataTable
     * @return Response
     */
    public function index(ChapterPageDataTable $chapterPageDataTable)
    {
        BreadcrumbsRegister::Register($this->ModelName, $this->BreadCrumbName);
        return $chapterPageDataTable->render('admin.chapter_pages.index', ['title' => $this->BreadCrumbName]);
    }

    /**
     * Show the form for creating a new ChapterPage.
     *
     * @return Response
     */
    public function create(Request $request)
    {
        BreadcrumbsRegister::Register($this->ModelName, $this->BreadCrumbName);
        return view('admin.chapter_pages.create')->with([
            'title'      => $this->BreadCrumbName,
            'chapter_id' => $request->get('chapter_id')
        ]);
    }

    /**
     * Store a newly created ChapterPage in storage.
     *
     * @param CreateChapterPageRequest $request
     *
     * @return Response
     */
    public function store(CreateChapterPageRequest $request)
    {
        $chapterPage = $this->chapterPageRepository->saveRecord($request);

        Flash::success($this->BreadCrumbName . ' saved successfully.');
        if (isset($request->continue)) {
            $redirect_to = redirect(route('admin.chapter-pages.create'));
        } elseif (isset($request->translation)) {
            $redirect_to = redirect(route('admin.chapter-pages.edit', $chapterPage->id));
        } else {
            $redirect_to = redirect(route('admin.chapter-pages.index'));
        }
        return $redirect_to->with([
            'title' => $this->BreadCrumbName
        ]);
    }

    /**
     * Display the specified ChapterPage.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $chapterPage = $this->chapterPageRepository->findWithoutFail($id);

        if (empty($chapterPage)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.chapter-pages.index'));
        }

        BreadcrumbsRegister::Register($this->ModelName, $this->BreadCrumbName, $chapterPage);
        return view('admin.chapter_pages.show')->with(['chapterPage' => $chapterPage, 'title' => $this->BreadCrumbName]);
    }

    /**
     * Show the form for editing the specified ChapterPage.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $chapterPage = $this->chapterPageRepository->findWithoutFail($id);

        if (empty($chapterPage)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.chapter-pages.index'));
        }

        BreadcrumbsRegister::Register($this->ModelName, $this->BreadCrumbName, $chapterPage);
        return view('admin.chapter_pages.edit')->with(['chapterPage' => $chapterPage, 'title' => $this->BreadCrumbName]);
    }

    /**
     * Update the specified ChapterPage in storage.
     *
     * @param int $id
     * @param UpdateChapterPageRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateChapterPageRequest $request)
    {
        $chapterPage = $this->chapterPageRepository->findWithoutFail($id);

        if (empty($chapterPage)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.chapter-pages.index'));
        }

        $chapterPage = $this->chapterPageRepository->updateRecord($request, $chapterPage);

        Flash::success($this->BreadCrumbName . ' updated successfully.');
        if (isset($request->continue)) {
            $redirect_to = redirect(route('admin.chapter-pages.create'));
        } else {
            $redirect_to = redirect(route('admin.chapter-pages.index'));
        }
        return $redirect_to->with(['title' => $this->BreadCrumbName]);
    }

    /**
     * Remove the specified ChapterPage from storage.
     *
     * @param int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $chapterPage = $this->chapterPageRepository->findWithoutFail($id);

        if (empty($chapterPage)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.chapter-pages.index'));
        }

        $this->chapterPageRepository->deleteRecord($id);

        Flash::success($this->BreadCrumbName . ' deleted successfully.');
        return redirect(route('admin.chapter-pages.index'))->with(['title' => $this->BreadCrumbName]);
    }
}

resources/views/admin/chapter_pages/create.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content')
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'admin.chapter-pages.store', 'files' => true]) !!}

                        @include('admin.chapter_pages.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/chapter_pages/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.chapter-pages.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    @ability('super-admin' ,'chapter-pages.show')
    <a href="{{ route('admin.chapter-pages.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    @endability
    @ability('super-admin' ,'chapter-pages.edit')
    <a href="{{ route('admin.chapter-pages.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    @endability
    @ability('super-admin' ,'chapter-pages.destroy')
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
    ]) !!}
    @endability
</div>
{!! Form::close() !!}

resources/views/admin/chapter_pages/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $chapterPage->name }} <small>{{ $title }}</small>
@endsection

@section('content')
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($chapterPage, ['route' => ['admin.chapter-pages.update', $chapterPage->id], 'method' => 'patch', 'files' => true]) !!}

                        @include('admin.chapter_pages.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/chapter_pages/fields.blade.php
<!-- Chapter Id Field -->


{!! Form::hidden('chapter_id', isset($chapter_id) ?$chapter_id :null, ['class' => 'form-control', 'placeholder'=>'Enter chapter_id']) !!}


<!-- Number Field -->
<div class="form-group col-sm-12">
    {!! Form::label('number', 'Page Number:') !!}
    {!! Form::text('number', null, ['class' => 'form-control', 'placeholder'=>'Enter Page number']) !!}
</div>
<div class="clearfix"></div>
<!-- Text Field -->
<div class="form-group col-sm-12">
    {!! Form::label('text', 'Text:') !!}
    {!! Form::textarea('details', null, ['class' => 'form-control', 'placeholder'=>'Enter text']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    @if(!isset($chapterPage))
        {!! Form::submit(__('Save And Add Translations'), ['class' => 'btn btn-primary', 'name'=>'translation']) !!}
    @endif
    {!! Form::submit(__('Save And Add More'), ['class' => 'btn btn-primary', 'name'=>'continue']) !!}
    <a href="{!! route('admin.chapter-pages.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/admin/chapter_pages/index.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content')
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('admin.chapter_pages.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/admin/chapter_pages/show.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content')
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    <dl class="dl-horizontal">
                        @include('admin.chapter_pages.show_fields')
                    </dl>
                    {!! Form::open(['route' => ['admin.chapter-pages.destroy', $chapterPage->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        @ability('super-admin' ,'chapter-pages.show')
                        <a href="{!! route('admin.chapter-pages.index') !!}" class="btn btn-default">
                            <i class="glyphicon glyphicon-arrow-left"></i> Back
                        </a>
                        @endability
                    </div>
                    <div class='btn-group'>
                        @ability('super-admin' ,'chapter-pages.edit')
                        <a href="{{ route('admin.chapter-pages.edit', $chapterPage->id) }}" class='btn btn-default'>
                            <i class="glyphicon glyphicon-edit"></i> Edit
                        </a>
                        @endability
                    </div>
                    <div class='btn-group'>
                        @ability('super-admin' ,'chapter-pages.destroy')
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i> Delete', [
                            'type' => 'submit',
                            'class' => 'btn btn-danger',
                            'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
                        ]) !!}
                        @endability
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/chapter_pages/show_fields.blade.php
<!-- Chapter Id Field -->
<dt>{!! Form::label('chapter_id', 'Chapter Id:') !!}</dt>
<dd>{!! $chapterPage->chapter_id !!}</dd>

<!-- Number Field -->
<dt>{!! Form::label('number', 'Number:') !!}</dt>
<dd>{!! $chapterPage->number !!}</dd>

<!-- Text Field -->
<dt>{!! Form::label('text', 'Text:') !!}</dt>
<dd>{!! $chapterPage->text !!}</dd>

resources/views/admin/chapter_pages/table.blade.php
@push('css')
    @include('admin.layouts.datatables_css')
@endpush

{!! $dataTable->table(['width' => '100%']) !!}

@push('scripts')
    @include('admin.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush